title: An open letter in support of RMS.
baseurl: ""
url: "https://rms-support-letter.github.io"

github_username: rms-support-letter
repository: rms-support-letter/rms-support-letter.github.io

collections:
  translations:
    output: true
    permalink: /:name:output_ext


# Build settings
theme: minima

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - migrate.py
  - CONTRIBUTING.md
  - README*.md
